spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/lghpoint_test?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: xinglong828

  jpa:
    open-in-view: true
    show-sql: true
    database-platform: org.hibernate.spatial.dialect.mysql.MySQLSpatialDialect